FROM gcc:4.9
RUN mkdir /app
COPY hello.c /app
WORKDIR /app
RUN gcc -DNAME=\"hello-scratch\" -o hello hello.c
CMD ["./hello"]

FROM scratch
COPY --from=0 /app/hello /app/hello
COPY --from=0 /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 
COPY --from=0 /lib/x86_64-linux-gnu/libc.so.6  /lib/x86_64-linux-gnu/libc.so.6
WORKDIR /app
CMD ["./hello"]
